version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      
  frontend:
    build: 
      context: front
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080